from admin.user.routes import blueprint as user_blueprint
from admin.product.routes import blueprint as product_blueprint
from admin.category.routes import blueprint as category_blueprint
from admin.order.routes import blueprint as order_blueprint
from admin.payment.routes import blueprint as payment_blueprint
from admin.address.routes import blueprint as address_blueprint
from admin.feedback.routes import blueprint as feedback_blueprint
from admin.auth.routes import blueprint as auth_blueprint
from admin.log.routes import blueprint as log_blueprint